[asana]
token= "your_asana_access_token"
base_url = "https://app.asana.com/api/1.0"




[fetch]
short_interval = "30s"
long_interval = "5m"
polling_interval = "30s"
second_polling_interval = "5m"


[cache]
path = "./.cache"

[refresh]
interval = "1m"
retry = 10

